### PR TITLE
Improve UX for Holo Search

### PR DESCRIPTION
**Pull request by friedger**
This PR 
- revert holo search default
- add bold italic style if search matches
- replace search action with undetermined action
- minor code improvements

screenshot_1493235355

### CODE REVIEW

**Comment by aperomsik** [comment]
Hi Friedger, 

What does IME_ACTION_UNSPECIFIED do here? 

I am not sure I understand the UX issue you are trying to address. You wrote "the item is added if you click the arrow or magnifying glass" -- but that is the intended behavior, as hinted by the "+" in the magnifying glass. What's wrong with it? 

The idea is to seamlessly combine search and add. I can type "milk" and if milk is already on my list I can mark it as needed it by clicking the + icon, probably before I even finish typing, or if it is not there yet I can immediately add it based on what I have already typed in the search box without typing it again.

**Comment by friedger** [comment]
IME_ACTION_UNSPECIFIED replaces the search icon in the soft keyboard by something general, e.g. "next" or an arrow.

The issue is that by pressing the search icon on the soft keyboard, I don't launch a search, instead three possible actions are available:
* if the name of the item does not exist then a new item is created and added
* if the name of the item exists and it is not in the list then the existing item is added to the list
* it the name of the item exists and it in the list then nothing happens

This is not clear from the UI.
To improve the UI, the action on the soft keyboard was replaced and the case when the name exists was made more apparent by changing the font style.

**Comment by friedger** [comment]
Now, I think we can remove the option to switch between holo search and add field at the bottom.

**Comment by aperomsik** [comment]
Thanks, Friedger, that's much clearer-- hadn't realized you were referring to the keyboard search button, which I never really noticed in this context. 

Aside from my confusion about which button you meant I was also wondering about performance impact of the italics processing. Tried it on my phone and it seems OK. Merged.

**Pull request merged**
